# Generated by Django 4.2.3 on 2023-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('theme', models.CharField(max_length=100)),
                ('num_days', models.PositiveIntegerField()),
                ('end_date', models.DateField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
