# Generated by Django 4.2.3 on 2023-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0002_budgetplanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikedMost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_visit', models.DateField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('liked_most', models.TextField()),
                ('overall_experience', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('disliked_most', models.ManyToManyField(to='travel_planner_app.dislikedmost')),
            ],
        ),
    ]
