# Generated by Django 4.2.3 on 2023-07-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0003_dislikedmost_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='disliked_most',
        ),
        migrations.AlterField(
            model_name='review',
            name='liked_most',
            field=models.CharField(choices=[('Beautiful Scenery', 'Beautiful Scenery'), ('Good Value for Money', 'Good Value for Money'), ('Peaceful Environment', 'Peaceful Environment'), ('Cozy Ambiance', 'Cozy Ambiance'), ('Delicious Food', 'Delicious Food'), ('Clean and Well-Maintained', 'Clean and Well-Maintained')], help_text='Select what you liked most about the place.', max_length=100),
        ),
        migrations.DeleteModel(
            name='DislikedMost',
        ),
        migrations.AddField(
            model_name='review',
            name='disliked_most',
            field=models.CharField(choices=[('Noisy Environment', 'Noisy Environment'), ('Overpriced', 'Overpriced'), ('Bad Location', 'Bad Location'), ('Poor Food Quality', 'Poor Food Quality')], default='Overpriced', help_text='Select what you disliked most about the place.', max_length=100),
        ),
    ]
