# Generated by Django 4.2.3 on 2023-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0004_remove_review_disliked_most_alter_review_liked_most_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='disliked_most',
            field=models.CharField(choices=[('Noisy Environment', 'Noisy Environment'), ('Overpriced', 'Overpriced'), ('Bad Location', 'Bad Location'), ('Poor Food Quality', 'Poor Food Quality')], max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='liked_most',
            field=models.CharField(choices=[('Beautiful Scenery', 'Beautiful Scenery'), ('Good Value for Money', 'Good Value for Money'), ('Peaceful Environment', 'Peaceful Environment'), ('Cozy Ambiance', 'Cozy Ambiance'), ('Delicious Food', 'Delicious Food'), ('Clean and Well-Maintained', 'Clean and Well-Maintained')], max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
