# Generated by Django 4.2.3 on 2023-07-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0005_alter_review_disliked_most_alter_review_liked_most_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='name_of_place',
        ),
    ]
