# Generated by Django 4.2.3 on 2023-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0008_remove_usersignup_email_alter_budgetplanner_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplanner',
            name='budget',
            field=models.DecimalField(decimal_places=2, default='1000', max_digits=10),
        ),
    ]
