# Generated by Django 4.2.3 on 2023-07-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0011_alter_budgetplanner_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplanner',
            name='theme',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
