# Generated by Django 4.2.3 on 2023-07-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0012_alter_budgetplanner_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplanner',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='budgetplanner',
            name='num_days',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='budgetplanner',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
