# Generated by Django 4.2.3 on 2023-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0013_alter_budgetplanner_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplanner',
            name='current_location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
